# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Spring Boot modules
        run: |
          cd app/water-quality-prediction
          mvn clean install -DskipTests

          cd ../chlorine-consumption
          mvn clean install -DskipTests

          cd ../flow-customization
          mvn clean install -DskipTests

          cd ../sensor-management
          mvn clean install -DskipTests

          cd ../notification-system
          mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for water-quality-prediction
        uses: docker/build-push-action@v4
        with:
          context: app/water-quality-prediction
          tags: kaveeshait21258794/24-25j-030-wq-server:prediction
          push: true

      - name: Build and push Docker images for chlorine-consumption
        uses: docker/build-push-action@v4
        with:
          context: app/chlorine-consumption
          tags: kaveeshait21258794/24-25j-030-wq-server:chlorine
          push: true

      - name: Build and push Docker images for flow-customization
        uses: docker/build-push-action@v4
        with:
          context: app/flow-customization
          tags: kaveeshait21258794/24-25j-030-wq-server:flow
          push: true

      - name: Build and push Docker images for sensor-management
        uses: docker/build-push-action@v4
        with:
          context: app/sensor-management
          tags: kaveeshait21258794/24-25j-030-wq-server:sensor
          push: true

      - name: Build and push Docker images for notification-system
        uses: docker/build-push-action@v4
        with:
          context: app/notification-system
          tags: kaveeshait21258794/24-25j-030-wq-server:notification
          push: true

      # - name: Build and push Docker images for model-service
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: app/model-service
      #     tags: kaveeshait21258794/24-25j-030-wq-server:model-service

