name: Java CI with Maven and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 using AdoptOpenJDK (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project with Maven from the app directory (parent POM)
      - name: Build the project with Maven
        run: mvn dependency:resolve-plugins
        working-directory: ./app  # Set working directory to 'app' where the parent POM is located

      # Step 4: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker image for main-application
      - name: Build and push Docker image for main-application
        uses: docker/build-push-action@v4
        with:
          context: ./app/main-application  # Docker context for the main application module
          tags: kaveeshait21258794/24-25j-030-wq-server:wq-server
          push: true
