name: Update README with Merged PRs

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with merged PR
        run: |
          echo "- **[#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})**: ${{ github.event.pull_request.title }}" >> README.md
          echo "  - Description: ${{ github.event.pull_request.body }}" >> README.md

      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://github.com/${{ github.repository }}
          git config --global credential.helper store

      - name: Commit and push changes to a new branch
        run: |
          # Ensure we're on main and get the latest updates
          git checkout main
          git pull origin main

          # Create a new branch based on main
          git checkout -b update-readme-pr-${{ github.event.pull_request.number }}

          # Stage and commit changes
          git add README.md
          git commit -m "Update README with PR #${{ github.event.pull_request.number }}"

          # Push the new branch to the remote repository
          git push origin update-readme-pr-${{ github.event.pull_request.number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.USER_TOKEN }}
          base: main  # Set the base branch to 'main'
          branch: update-readme-pr-${{ github.event.pull_request.number }}
          title: "Update README with PR #${{ github.event.pull_request.number }}"
          body: |
            This PR updates the README with details of the recently merged pull request.

            - **PR Title:** ${{ github.event.pull_request.title }}
            - **PR Link:** [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})
            - **Description:** ${{ github.event.pull_request.body }}

            Please review and merge this PR to keep the README up to date.
          labels: documentation

      - name: Merge Pull Request
        if: success()  # Merge the PR after it is created
        uses: peter-evans/enable-pull-request-merge@v2
        with:
          token: ${{ secrets.USER_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
