name: Update README with Merged PRs

on:
  pull_request:
    types: [closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with merged PR
        run: |
          echo "- **[#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})**: ${{ github.event.pull_request.title }}" >> README.md
          echo "  - Description: ${{ github.event.pull_request.body }}" >> README.md

      - name: Configure Git for committing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create commit and push changes
        run: |
          git commit -m "Update README with PR #${{ github.event.pull_request.number }}" -b update-readme-pr-${{ github.event.pull_request.number }}
          git push origin HEAD:update-readme-pr-${{ github.event.pull_request.number }}

# Alternative approach (direct push, requires protected branch configuration)
# - name: Create commit and push changes (direct push)
#   run: |
#     git commit -m "Update README with PR #${{ github.event.pull_request.number }}" ${{ github.event.pull_request.base.ref }}
#     git push origin ${{ github.event.pull_request.base.ref }}
